M48
; DRILL file KiCad 10.0.5 date 2026-08-13T01:18:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-13T01:18:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.020
%
G90
G05
T1
X55.21Y-61.1
X55.21Y-66.9
T2
X56.53Y-77.075
X56.53Y-83.425
M30
